Fix UnboundLocalError about 'argument_parser' in Options
The except clause in Options.__init__() refers to 'argument_parser'
variable which was only defined in an "if" clause. This results in the
following error:

  UnboundLocalError: local variable 'argument_parser' referenced before assignment

Move 'argument_parser' definition at function's global scope.