Import of GitHub PR #1734: Support Windows... somewhat
In order to support windows, we need to use the c++-standard named struct params like @HexDecimal suggested in https://github.com/google/pytype/issues/1154#issuecomment-1108459343 and change cxx_std=11 to 20 like @rchen152 suggested in https://github.com/google/pytype/issues/1154#issuecomment-1377994508.

There may be more changes required. In particular, I am getting *one* test failing in the Tests step[^1] of the CI:
```
    File "D:\a/pytype/pytype/out\pytype\io_test.py", line 169, in test_unused_imports_info_files
      self.assertEqual(0, ret)
  AssertionError: 0 != 1
    ⋮
   FAILED: pytype/io_test.log D:/a/pytype/pytype/out/pytype/io_test.log
  C:\Windows\system32\cmd.exe /C "cd /D D:\a\pytype\pytype\out\pytype && C:\Python\Lib\site-packages\cmake\data\bin\cmake.exe -E env TYPESHED_HOME=D:/a/pytype/pytype/typeshed C:/Python/python.exe -B D:/a/pytype/pytype/build_scripts/test_module.py pytype.io_test -o D:/a/pytype/pytype/out/pytype/io_test.log -P D:/a/pytype/pytype/out -s -p"
  C:\Users\runneradmin\AppData\Local\Temp\tmp2coltc1x\m.py:1:1: error: in <module>: Can't find module 'common.foo'. [import-error]

  from common import foo; print(foo.x)~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ```
 I don't know why. But this is still an incremental improvement in Windows support for pytype.

 [^1]: Additionally, in my [repo](https://github.com/wyattscarpenter/pytype/actions/runs/10342876412/jo[]#step:6:289), I've changed the CI script to run all of the checks and not early-out; in this, the Windows version now passes the Extensions Tests and gets some error in Type Check.

PiperOrigin-RevId: 662898874