Return a version tuple instead of a version list in analyze_project.utils.
In a Python interpreter:
>>> 'python%d.%d' % [3, 6]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: %d format: a number is required, not list
>>> 'python%d.%d' % (3, 6)
'python3.6'

--
PiperOrigin-RevId: 195174456
MOS_MIGRATED_REVID=195174456