Rollback of commit 9812e5131cb552c67408d8a9faf27fd08aaeba8d.
*** Reason for rollback ***

ERROR: pyglib/thread_pool/BUILD:800:1 Checking types for pyglib/thread_pool/thread_pool.py failed (Exit 1) pytype.par failed: error executing command tools/python/pytype/pytype.par --check '--touch=blaze-out/k8-fastbuild/bin/pyglib/thread_pool/pytype-aspect/thread_pool@pytype@check/thread_pool.check' ... (remaining 8 argument(s) skipped) [forge_remote_host=ixkm3].
File "thread_pool.py", line 942, in _StartWorkers: No attribute 'moves' on module 'six' [module-attr]

*** Original change description ***

Add support for the @six.add_metaclass decorator.

* Add a pyi file from typeshed to third_party/py/six
* Add an overlay for six.add_metaclass
* Defer checking for a class with abstract methods inheriting from ABCMeta
  until after class decorators are applied.

***

--
PiperOrigin-RevId: 178149221
MOS_MIGRATED_REVID=178149221